# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-11-29 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_username', models.CharField(max_length=64)),
                ('a_password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CollecTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Jobinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobname', models.CharField(max_length=64)),
                ('company_name', models.CharField(max_length=64)),
                ('position', models.CharField(max_length=64)),
                ('eduLevel', models.CharField(max_length=16)),
                ('city_name', models.CharField(max_length=32)),
                ('salary', models.CharField(max_length=32)),
                ('update_time', models.CharField(max_length=32)),
                ('workingExp', models.CharField(max_length=16)),
                ('web_name', models.CharField(max_length=32)),
                ('hash_id', models.CharField(max_length=128)),
                ('job_require', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_username', models.CharField(max_length=64)),
                ('u_password', models.CharField(max_length=64)),
                ('u_phone', models.CharField(max_length=32)),
                ('u_email', models.CharField(max_length=64)),
                ('u_token', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='collectable',
            name='jobinfo_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpro.Jobinfo'),
        ),
        migrations.AddField(
            model_name='collectable',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpro.User'),
        ),
    ]
